// Generated by scripts/generate-footprint.mjs from assets/map-pyxis.png — do not edit by hand.

export type MapPoint = { x: number; y: number };

export const footprintMap = {
  src: "/images/map/footprint.svg",
  width: 1142,
  height: 618,
} as const;

/** Headquarters (Tunis): origin of the network lines. */
export const footprintHub: MapPoint = { x: 581, y: 195 };

/** Other offices (United Kingdom). */
export const footprintOffices: MapPoint[] = [{"x":542,"y":105}];

/** Centroids of project countries (neighbouring countries and islands grouped). */
export const footprintProjects: MapPoint[] = [{"x":200,"y":242},{"x":293,"y":334},{"x":313,"y":490},{"x":328,"y":575},{"x":530,"y":318},{"x":541,"y":231},{"x":557,"y":137},{"x":595,"y":317},{"x":634,"y":487},{"x":651,"y":230},{"x":693,"y":201},{"x":711,"y":442},{"x":912,"y":362},{"x":955,"y":356},{"x":1031,"y":371}];
