// Generated by scripts/generate-footprint.mjs from assets/map-pyxis.png — do not edit by hand.
// Country points and their projection live in src/data/countries.ts.

export const footprintMap = {
  src: "/images/map/footprint.svg",
  width: 1142,
  height: 618,
} as const;
